sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f client/Dockerfile.dev -t jurglic/docker-multi-test client

script:
  - docker run jurglic/docker-multi-test npm test -- --coverage

after_success:
  - docker build -t jurglic/docker-multi-client client
  - docker build -t jurglic/docker-multi-nginx nginx
  - docker build -t jurglic/docker-multi-server server
  - docker build -t jurglic/docker-multi-worker worker
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
  - docker push jurglic/docker-multi-client
  - docker push jurglic/docker-multi-nginx
  - docker push jurglic/docker-multi-server
  - docker push jurglic/docker-multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-578721371953"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
